default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *default
  database: iut_calendar_development
test:
  <<: *default
  database: iut_calendar_test
production:
  <<: *default
  database: iut_calendar_production
