# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 861b20e2cd101b5a648bd2aecfaeae0486ac0529b2199bcfef16fed7518a8ee6379536bd113700afe6d756181ed7c1fd88a57a97dec1f4b90c6f9b2adec59bfa

test:
  secret_key_base: aad25588bd12a179d75b4c4c3e0faff29048f86a6b8c5e5a1930f14c16a68d15d190639afa42027b7b08f1af6d321a9be828c8a35f29c3635e6481d264d3d8c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
